# Generated by Django 3.0.7 on 2020-06-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
